# Generated by Django 4.2.5 on 2023-10-24 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('mpg', models.PositiveIntegerField(verbose_name='Mileage (mpg)')),
                ('rep78', models.PositiveIntegerField(verbose_name='Repair record 1978')),
                ('headroom', models.PositiveIntegerField(verbose_name='Headroom (in.)')),
                ('trunk', models.PositiveIntegerField(verbose_name='Headroom (in.)')),
                ('weight', models.PositiveIntegerField(verbose_name='Weight (lbs.)')),
                ('length', models.PositiveIntegerField(verbose_name='Length (in.)')),
                ('turn', models.PositiveIntegerField(verbose_name='Turn circle (ft.)')),
                ('displacement', models.PositiveIntegerField(verbose_name='Displacement (cu. in.)')),
                ('gear_ratio', models.PositiveIntegerField(verbose_name='Gear ratio')),
                ('foreign', models.BooleanField(verbose_name='Car origin (foreign)')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.make')),
            ],
        ),
    ]
