# Generated by Django 4.2.5 on 2023-10-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='headroom',
            field=models.FloatField(verbose_name='Headroom (in.)'),
        ),
    ]
