# Generated by Django 4.2.5 on 2023-10-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_alter_auto_headroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='gear_ratio',
            field=models.FloatField(verbose_name='Gear ratio'),
        ),
    ]
