# Generated by Django 4.2.5 on 2023-10-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_alter_auto_gear_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='rep78',
            field=models.PositiveIntegerField(null=True, verbose_name='Repair record 1978'),
        ),
    ]
